FilmNetWeb/Models/ViewModels/UserDetailsViewModel.cs
using FilmNetWeb.DAL;
using FilmNetWeb.DAL.Repositories;
using FilmNetWeb.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FilmNetWeb.Models.ViewModels
{
    public class UserDetailsViewModel
    {
        public string UserId { get; set; }
        public string UserName { get; set; }

        public List<Rating> ratings;

        public UserDetailsViewModel(ApplicationUser user)
        {
            Initialize(user);
        }

        private void Initialize(ApplicationUser user)
        {
            UserId = user.Id;
            UserName = user.UserName;
            ratings = user.Ratings.ToList();
        }
    }
}

FilmNetWeb/Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FilmNetWeb.DAL;
using FilmNetWeb.Models.Entities;
using FilmNetWeb.DAL.Repositories;
using FilmNetWeb.Tools;
using PagedList;
using FilmNetWeb.DAL.Abstract;

namespace FilmNetWeb.Controllers
{
    public class ActorsController : Controller
    {
        private IRepository<Actor> repository;

        public ActorsController(IRepository<Actor> _repository)
        {
            this.repository = _repository;
        }

        public ActionResult Index(string sortOrder, string searchString, int? page)
        {
            var actorsList = GetActors(sortOrder, searchString, page);

            return View("Index", actorsList);
        }
        
        public ActionResult ActorsList(string sortOrder, string searchString, int? page)
        {
            var actorsList = GetActors(sortOrder, searchString, page);
            return PartialView("_ActorsList", actorsList);
        }

        [NonAction]
        private IPagedList<Actor> GetActors(string sortOrder, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentSearchString = searchString;

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.SurnameSortParm = sortOrder == "surname" ? "surname_desc" : "surname";

            var actorsFilter = ExpressionBuilder.BuildActorFilter(searchString);
            var sortActors = ExpressionBuilder.BuildActorOrderBy(sortOrder);

            var actorsList = repository.Get(actorsFilter, sortActors);

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return actorsList.ToPagedList(pageNumber, pageSize);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actor actor = repository.SingleOrDefault(x => x.ActorId == id);
            if (actor == null)
            {
                return HttpNotFound();
            }
            return View(actor);
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Surname,Description")] Actor actor)
        {
            if (ModelState.IsValid)
            {
                repository.Insert(actor);
                repository.Save();
                return RedirectToAction("Index");
            }

            return View(actor);
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actor actor = repository.SingleOrDefault(x => x.ActorId == id);
            if (actor == null)
            {
                return HttpNotFound();
            }
            return View(actor);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ActorId,Name,Surname,Description")] Actor actor)
        {
            if (ModelState.IsValid)
            {
                repository.Update(actor);
                repository.Save();
                return RedirectToAction("Index");
            }
            return View(actor);
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actor actor = repository.SingleOrDefault(x => x.ActorId == id);
            if (actor == null)
            {
                return HttpNotFound();
            }
            return View(actor);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Actor actor = repository.SingleOrDefault(x => x.ActorId == id);
            repository.Delete(actor);
            repository.Save();
            return RedirectToAction("Index");
        }
    }
}

FilmNetWeb/Controllers/FilmsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FilmNetWeb.DAL;
using FilmNetWeb.Models.Entities;
using FilmNetWeb.DAL.Repositories;
using FilmNetWeb.Tools;
using PagedList;
using Microsoft.AspNet.Identity;
using FilmNetWeb.DAL.Abstract;

namespace FilmNetWeb.Controllers
{
    public class FilmsController : Controller
    {
        private IFilmRepository filmsRepository;
        private IRepository<ActorRole> rolesRepository;
        private IRepository<Actor> actorsRepository;
        private IRepository<Genre> genresRepository;
        private IRatingRepository ratingsRepository;

        public FilmsController(IFilmRepository _filmsRepository, IRepository<ActorRole> _rolesRepository, IRepository<Actor> _actorsRepository,
                               IRepository<Genre> _genresRepository, IRatingRepository _ratingsRepository)
        {
            this.filmsRepository = _filmsRepository;
            this.rolesRepository = _rolesRepository;
            this.actorsRepository = _actorsRepository;
            this.genresRepository = _genresRepository;
            this.ratingsRepository = _ratingsRepository;
        }

        public ActionResult Index(string sortOrder, string searchString, string genreFilter, int? page)
        {
            List<SelectListItem> genresCombo = new List<SelectListItem>();

            var genres = genresRepository.Get();
            genresCombo.Add(new SelectListItem() { Text = "" });
            foreach(var g in genres)
            {
                genresCombo.Add(new SelectListItem() { Text = g.Name, Value=g.Name });
            }
            ViewBag.GenresCombo = genresCombo;

            var filmsList = GetFilms(sortOrder, searchString, genreFilter, page);

            return View("Index", filmsList);
        }

        public ActionResult FilmsList(string sortOrder, string searchString, string genreFilter, int? page)
        {
            var filmsList = GetFilms(sortOrder, searchString, genreFilter, page);

            return PartialView("_FilmsList", filmsList);
        }

        [NonAction]
        private IPagedList<Film> GetFilms(string sortOrder, string searchString, string genreFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentSearchString = searchString;
            ViewBag.CurrentGenre = genreFilter;

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.YearSortParm = sortOrder == "year" ? "year_desc" : "year";
            ViewBag.AverageSortParm = sortOrder == "average" ? "average_desc" : "average";

            var filter = ExpressionBuilder.BuildFilmFilter(searchString, genreFilter);
            var sortFilms = ExpressionBuilder.BuildFilmOrderBy(sortOrder);

            var filmsList = filmsRepository.Get(filter, sortFilms, "Genre");

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return filmsList.ToPagedList(pageNumber, pageSize);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = filmsRepository.SingleOrDefault(x => x.FilmId == id);
            if (film == null)
            {
                return HttpNotFound();
            }
            return View(film);
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            ViewBag.GenreId = new SelectList(genresRepository.Get(), "GenreId", "Name");
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GenreId,Name,Description,Year")] Film film)
        {
            if (ModelState.IsValid)
            {
                filmsRepository.Insert(film);
                filmsRepository.Save();
                return RedirectToAction("Edit", new { id = film.FilmId });
            }

            ViewBag.GenreId = new SelectList(genresRepository.Get(), "GenreId", "Name", film.GenreId);
            return View(film);
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = filmsRepository.SingleOrDefault(x => x.FilmId == id);
            if (film == null)
            {
                return HttpNotFound();
            }

            List<SelectListItem> actorsCombo = new List<SelectListItem>();
            var actors = actorsRepository.Get();
            actorsCombo.Add(new SelectListItem() { Text = "" });
            foreach (var a in actors)
            {
                actorsCombo.Add(new SelectListItem() { Text = a.Name + " " + a.Surname, Value = a.ActorId.ToString()});
            }
            ViewBag.ActorId = actorsCombo;

            ViewBag.GenreId = new SelectList(genresRepository.Get(), "GenreId", "Name", film.GenreId);
            return View(film);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FilmId,GenreId,Name,Description,Year")] Film film)
        {
            if (ModelState.IsValid)
            {
                filmsRepository.Update(film);
                filmsRepository.Save();
                return RedirectToAction("Index");
            }
            ViewBag.GenreId = new SelectList(genresRepository.Get(), "GenreId", "Name", film.GenreId);
            return View(film);
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = filmsRepository.SingleOrDefault(x => x.FilmId == id);
            if (film == null)
            {
                return HttpNotFound();
            }
            return View(film);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Film film = filmsRepository.SingleOrDefault(x => x.FilmId == id);
            filmsRepository.Delete(film);
            filmsRepository.Save();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult DeleteRole(int filmId, int actorId)
        {
            ActorRole role = rolesRepository.SingleOrDefault(x => x.FilmId == filmId && x.ActorId == actorId);
            rolesRepository.Delete(role);
            rolesRepository.Save();
            var roles = rolesRepository.Get(x => x.FilmId == filmId);
            return PartialView("_RolesGrid", roles);
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult AddRole(ActorRole role)
        {
            var roleToUpdate = rolesRepository.SingleOrDefault(x => x.FilmId == role.FilmId && x.ActorId == role.ActorId);
            if(role.ActorId == 0 || String.IsNullOrEmpty(role.Name))
            {
                var oldRoles = rolesRepository.Get(x => x.FilmId == role.FilmId, includeProperties: "Actor");
                return PartialView("_RolesGrid", oldRoles);
            }
            if (roleToUpdate == null)
            {
                rolesRepository.Insert(role);
                
            }
            else
            {
                roleToUpdate.Name = role.Name;
                rolesRepository.Update(roleToUpdate);
            }
            rolesRepository.Save();

            var roles = rolesRepository.Get(x => x.FilmId == role.FilmId, includeProperties:"Actor");
            return PartialView("_RolesGrid", roles);
        }

        [Authorize]
        public ActionResult AddRating(Rating rating)
        {
            rating.UserId = User.Identity.GetUserId();
            var ratingToUpdate = ratingsRepository.SingleOrDefault(x => x.FilmId == rating.FilmId && x.UserId == rating.UserId);

            if (ratingToUpdate == null)
            {
                ratingsRepository.AddRating(rating);
            }
            else
            {
                ratingToUpdate.Comment = rating.Comment;
                ratingToUpdate.UserRating = rating.UserRating;
                ratingsRepository.UpdateRating(ratingToUpdate);
            }
            ratingsRepository.Save();

            var ratings = ratingsRepository.Get(x => x.FilmId == rating.FilmId, includeProperties:"User");
            return PartialView("_RatingsList", ratings);
        }
    }
}

FilmNetWeb/Controllers/SystemController.cs
using FilmNetWeb.DAL;
using FilmNetWeb.DAL.Abstract;
using FilmNetWeb.DAL.Repositories;
using FilmNetWeb.Models.Entities;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FilmNetWeb.Controllers
{
    public class SystemController : Controller
    {
        private IRepository<Log> logsRepository;

        public SystemController(IRepository<Log> _logsRepository)
        {
            this.logsRepository = _logsRepository;
        }

        public ActionResult Index(int ? page)
        {
            var logs = logsRepository.Get(orderBy: list => list.OrderByDescending(x => x.Date));

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            var logsList = logs.ToPagedList(pageNumber, pageSize);

            return View(logsList);
        }
    }
}

FilmNetWeb/Views/Shared/_ActorsList.cshtml
@model PagedList.IPagedList<FilmNetWeb.Models.Entities.Actor>
@using PagedList.Mvc;

<table class="table">
    <tr>
        <th>
            @Ajax.ActionLink("Imię", "ActorsList", new { searchString = ViewBag.CurrentSearchString, sortOrder = ViewBag.NameSortParm },
                   new AjaxOptions
                   {
                       UpdateTargetId = "actors-list",
                       InsertionMode = InsertionMode.Replace,
                       HttpMethod = "GET"
                   })
        </th>
        <th>
            @Ajax.ActionLink("Nazwisko", "ActorsList", new { searchString = ViewBag.CurrentSearchString, sortOrder = ViewBag.SurnameSortParm },
                   new AjaxOptions
                   {
                       UpdateTargetId = "actors-list",
                       InsertionMode = InsertionMode.Replace,
                       HttpMethod = "GET"
                   })
        </th>
        <th>
            Opis
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                <div class="ellipsis" style="width:650px">
                    @Html.DisplayFor(modelItem => item.Description)
                </div>
            </td>
            <td>
                @Html.ActionLink("Pełny opis", "Details", new { id = item.ActorId })
                @if (this.User.IsInRole("Administrator"))
                {
                @Html.ActionLink("Edytuj", "Edit", new { id = item.ActorId, }, new { style = "margin: 0 10px;" })
                @Html.ActionLink("Usuń", "Delete", new { id = item.ActorId })
                }
            </td>
        </tr>
    }
</table>
Strona @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) z @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
new { page, searchString = ViewBag.CurrentSearchString, sortOrder = ViewBag.CurrentSort, genreFilter = ViewBag.CurrentGenre }))

FilmNetWeb/Views/Shared/_FilmsList.cshtml
@model PagedList.IPagedList<FilmNetWeb.Models.Entities.Film>
@using PagedList.Mvc;

<table class="table">
    <tr>
        <th>
            @Ajax.ActionLink("Tytuł", "FilmsList", new { searchString = ViewBag.CurrentSearchString, sortOrder = ViewBag.NameSortParm, genreFilter = ViewBag.CurrentGenre, page = 1 },
                   new AjaxOptions
                   {
                       UpdateTargetId = "films-list",
                       InsertionMode = InsertionMode.Replace,
                       HttpMethod = "GET"
                   })
        </th>
        <th>
            Tytuł
        </th>
        <th>
            @Ajax.ActionLink("Rok wydania", "FilmsList", new { searchString = ViewBag.CurrentSearchString, sortOrder = ViewBag.YearSortParm, genreFilter = ViewBag.CurrentGenre, page = 1 },
                   new AjaxOptions
                   {
                       UpdateTargetId = "films-list",
                       InsertionMode = InsertionMode.Replace,
                       HttpMethod = "GET"
                   })
        </th>
        <th>
            @Ajax.ActionLink("Średnia", "FilmsList", new { searchString = ViewBag.CurrentSearchString, sortOrder = ViewBag.AverageSortParm, genreFilter = ViewBag.CurrentGenre, page = 1 },
                   new AjaxOptions
                   {
                       UpdateTargetId = "films-list",
                       InsertionMode = InsertionMode.Replace,
                       HttpMethod = "GET"
                   })
        </th>

        <th>
            Opis
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Average)
            </td>
            <td>
                <div class="ellipsis">
                    @Html.DisplayFor(modelItem => item.Description)
                </div>
            </td>
            <td>
                @Html.ActionLink("Pełny opis", "Details", new { id = item.FilmId }) 
                @if (this.User.IsInRole("Administrator"))
                {
                    @Html.ActionLink("Edytuj", "Edit", new { id = item.FilmId }, new { style = "margin: 0 10px;" }) 
                    @Html.ActionLink("Usuń", "Delete", new { id = item.FilmId })
                }
            </td>
        </tr>
    }
</table>
Strona @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) z @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
new { page, searchString = ViewBag.CurrentSearchString, sortOrder = ViewBag.CurrentSort, genreFilter = ViewBag.CurrentGenre }))

FilmNetWeb/Views/Shared/_InvitationsList.cshtml
@model IEnumerable<FilmNetWeb.Models.ViewModels.PendingInvitationViewModel>

@if (Model.Count() == 0)
{
    <p style="text-align:center;">Brak oczekujących zaproszeń</p>
}
else
{
<table class="table" id="invitations-list" style="margin:0 auto;width:auto;">
    <tr>
        <th>
            Zaproszenie od
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td style="vertical-align:middle;">
                @{
                    @Html.DisplayFor(modelItem => item.SenderName)
                }
            </td>
            <td class="invitation-buttons">
                @Ajax.ActionLink("Akceptuj", "AcceptInvitation", new { senderId = item.SenderId },
                                     new AjaxOptions
                                     {
                                         UpdateTargetId = "invitations-list",
                                         InsertionMode = InsertionMode.Replace,
                                         HttpMethod = "POST"
                                     }, new { @class = "btn btn-default btn-bold" })
                @Ajax.ActionLink("Odrzuć", "DeclineInvitation", new { senderId = item.SenderId },
                                     new AjaxOptions
                                     {
                                         UpdateTargetId = "invitations-list",
                                         InsertionMode = InsertionMode.Replace,
                                         HttpMethod = "POST"
                                     }, new { @class = "btn btn-default btn-bold" })
            </td>
        </tr>
                    }
</table>
}

FilmNetWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type = 'text/javascript' >
        var appInsights=window.appInsights||function(config)
        {
            function r(config){ t[config] = function(){ var i = arguments; t.queue.push(function(){ t[config].apply(t, i)})} }
            var t = { config:config},u=document,e=window,o='script',s=u.createElement(o),i,f;for(s.src=config.url||'//az416426.vo.msecnd.net/scripts/a/ai.0.js',u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=['Event','Exception','Metric','PageView','Trace','Ajax'];i.length;)r('track'+i.pop());return r('setAuthenticatedUserContext'),r('clearAuthenticatedUserContext'),config.disableExceptionTracking||(i='onerror',r('_'+i),f=e[i],e[i]=function(config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t['_' + i](config, r, u, e, o),s}),t
        }({
            instrumentationKey:'bf883216-fc74-491f-bd95-0f5f2939ad0b'
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FilmNet", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Filmy", "Index", "Films")</li>
                    <li>@Html.ActionLink("Aktorzy", "Index", "Actors")</li>
                    @if (Request.IsAuthenticated)
                    {
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Znajomi
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Twoi znajomi", "Index", "Friends")</li>
                            <li>@Html.ActionLink("Zaproś znajomego", "InviteFriend", "Friends")</li>
                            <li>@Html.ActionLink("Oczekujące zaproszenia", "PendingInvitations", "Friends")</li>
                        </ul>
                    </li>
                        if (this.User.IsInRole("Administrator"))
                        {
                        <li>@Html.ActionLink("Logi", "Index", "System")</li>
                        }
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    <footer>
        <p>&copy; @DateTime.Now.Year - FilmNet</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryunobtrusive")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FilmNetWeb/Views/Shared/_RatingsList.cshtml
@model IEnumerable<FilmNetWeb.Models.Entities.Rating>


<table class="table ratings-list">
    <tr>
        <th>
            Użytkownik
        </th>
        <th>
            Ocena
        </th>
        <th>
            Komentarz
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @{
                    var user = item.User.UserName;
                    @Html.DisplayFor(modelItem => user)
                }
            </td>
            <td>
                @{
                    var rating = item.UserRating;
                    @Html.DisplayFor(modelItem => rating)
                }
            </td>
            <td>
                @{
                    var comment = item.Comment;
                    @Html.DisplayFor(modelItem => comment)
                }
            </td>
        </tr>
    }
</table>

FilmNetWeb/Views/Shared/_RolesGrid.cshtml
@model IEnumerable<FilmNetWeb.Models.Entities.ActorRole>


<table class="table roles-list">
    <tr>
        <th>
            Aktor
        </th>
        <th>
            Rola
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @{
                    string actorName = item.Actor.Name + " " + item.Actor.Surname;
                    @Html.DisplayFor(modelItem => actorName)
                }
            </td>
            <td>
                @{
                    string role = item.Name;
                    @Html.DisplayFor(modelItem => role)
                }
            </td>
            <td>
                @Ajax.ActionLink("Delete", "DeleteRole", new { filmId = item.FilmId, actorId = item.ActorId },
                    new AjaxOptions
                    {
                        UpdateTargetId = "roles-grid",
                        InsertionMode = InsertionMode.Replace,
                        HttpMethod = "POST"
                    })
            </td>
        </tr>
     }
</table>

FilmNetWeb/Views/Shared/_userDetails.cshtml
@model FilmNetWeb.Models.ViewModels.UserDetailsViewModel

<h2>@Model.UserName</h2>

<h5>Oceny użytkownika</h5>
<table class="table">
    <tr>
        <th>
            Film
        </th>
        <th>
            Ocena
        </th>
        <th>
            Komentarz
        </th>
    </tr>

    @foreach (var item in Model.ratings)
    {
        <tr>
            <td>
                @{
                    var filmName = item.Film.Name;
                    @Html.DisplayFor(modelItem => filmName)
                }
            </td>
            <td>
                @{
                    var userRating = item.UserRating;
                    @Html.DisplayFor(modelItem => userRating)
                }
            </td>
            <td>
                @{
                    var comment = item.Comment;
                    @Html.DisplayFor(modelItem => comment)
                }
            </td>
        </tr>
     }
</table>